
#Fix NULLs for country values
astro_db.loc[astro_db['astronaut_name'] == "Neil A. Armstrong", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert S. Kimbrough", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "K. Megan McArthur", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dr. Chris Boshuizen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dr. Sian Proctor", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John B. McKay", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael J. Adams", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Tang Hongbo", 'country'] = "China"
astro_db.loc[astro_db['astronaut_name'] == "Wally Funk", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James A. Lovell Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas P. Stafford", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John W. Young", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Eugene A. Cernan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles Conrad Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard F. Gordon Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Alan L. Bean", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John L. Swigert Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Fred W. Haise Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Vladimir G. Titov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Crippen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jon A. McBride", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kathryn D. Sullivan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David C. Leestma", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Paul D. Scully-Power", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joe H. Engle", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Virgil I. Grissom", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph A. Walker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James A. McDivitt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Edward H. White II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "L. Gordon Cooper Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Walter M. Schirra Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William A. Anders", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David R. Scott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Russell L. Schweickart", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Alfred M. Worden", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James B. Irwin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ronald E. Evans Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Harrison H. Schmitt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph P. Kerwin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Paul J. Weitz", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Owen K. Garriott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jack R. Lousma", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Oleg G. Makarov", 'country'] = "USSR"
astro_db.loc[astro_db['astronaut_name'] == "Gerald P. Carr", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Edward G. Gibson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William R. Pogue", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Vance D. Brand", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donald K. Slayton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Yury V. Malyshev", 'country'] = "USSR"

astro_db.loc[astro_db['astronaut_name'] == "C. Gordon Fullerton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas K. Mattingly II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Henry W. Hartsfield Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert F. Overmyer", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph P. Allen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William B. Lenoir", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Frederick H. Hauck", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John M. Fabian", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Norman E. Thagard", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard H. Truly", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Daniel C. Brandenstein", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Guion S. Bluford Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dale A. Gardner", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William E. Thornton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Francis R. Scobee", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Terry J. Hart", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James D. van Hoften", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "George D. Nelson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael L. Coats", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard M. Mullane", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Steven A. Hawley", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Judith A. Resnik", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "Charles D. Walker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David M. Walker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Anna L. Fisher", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Karol J. Bobko", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donald E. Williams", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Margaret R. Seddon", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "S. David Griggs", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jeffrey A. Hoffman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Frederick D. Gregory", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Don L. Lind", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Taylor G. Wang", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John O. Creighton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Steven R. Nagel", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Shannon W. Lucid", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sultan bin Salman Al Saud", 'country'] = "Saudi Arabia"
astro_db.loc[astro_db['astronaut_name'] == "Roy D. Bridges Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Karl G. Henize", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "F. Story Musgrave", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Anthony W. England", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Loren W. Acton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John-David F. Bartoe", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard O. Covey", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John M. Lounge", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William F. Fisher", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Aleksandr A. Volkov", 'country'] = "USSR"
astro_db.loc[astro_db['astronaut_name'] == "Bonnie J. Dunbar", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James F. Buchli", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Gibson", 'country'] = "United States of America"
# astro_db.loc[astro_db['astronaut_name'] == "", 'country'] = "United States of America"
# astro_db.loc[astro_db['astronaut_name'] == "", 'country'] = "United States of America"
# astro_db.loc[astro_db['astronaut_name'] == "", 'country'] = "United States of America"

