
#Fix NULLs for country values
astro_db.loc[astro_db['astronaut_name'] == "Neil A. Armstrong", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert S. Kimbrough", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "K. Megan McArthur", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dr. Chris Boshuizen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dr. Sian Proctor", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John B. McKay", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael J. Adams", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Tang Hongbo", 'country'] = "China"
astro_db.loc[astro_db['astronaut_name'] == "Wally Funk", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James A. Lovell Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas P. Stafford", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John W. Young", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Eugene A. Cernan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles Conrad Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard F. Gordon Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Alan L. Bean", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John L. Swigert Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Fred W. Haise Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Vladimir G. Titov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Crippen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jon A. McBride", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kathryn D. Sullivan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David C. Leestma", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Paul D. Scully-Power", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joe H. Engle", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Virgil I. Grissom", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph A. Walker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James A. McDivitt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Edward H. White II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "L. Gordon Cooper Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Walter M. Schirra Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William A. Anders", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David R. Scott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Russell L. Schweickart", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Alfred M. Worden", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James B. Irwin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ronald E. Evans Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Harrison H. Schmitt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph P. Kerwin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Paul J. Weitz", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Owen K. Garriott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jack R. Lousma", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Oleg G. Makarov", 'country'] = "USSR"
astro_db.loc[astro_db['astronaut_name'] == "Gerald P. Carr", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Edward G. Gibson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William R. Pogue", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Vance D. Brand", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donald K. Slayton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Yury V. Malyshev", 'country'] = "USSR"
