
#Fix NULLs for country values
astro_db.loc[astro_db['astronaut_name'] == "Neil A. Armstrong", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert S. Kimbrough", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "K. Megan McArthur", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dr. Chris Boshuizen", 'country'] = "Australia"
astro_db.loc[astro_db['astronaut_name'] == "Dr. Sian Proctor", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John B. McKay", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael J. Adams", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Tang Hongbo", 'country'] = "China"
astro_db.loc[astro_db['astronaut_name'] == "Wally Funk", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James A. Lovell Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas P. Stafford", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John W. Young", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Eugene A. Cernan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles Conrad Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard F. Gordon Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Alan L. Bean", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John L. Swigert Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Fred W. Haise Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Vladimir G. Titov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Crippen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jon A. McBride", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kathryn D. Sullivan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David C. Leestma", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Paul D. Scully-Power", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joe H. Engle", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Virgil I. Grissom", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph A. Walker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James A. McDivitt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Edward H. White II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "L. Gordon Cooper Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Walter M. Schirra Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William A. Anders", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David R. Scott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Russell L. Schweickart", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Alfred M. Worden", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James B. Irwin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ronald E. Evans Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Harrison H. Schmitt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph P. Kerwin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Paul J. Weitz", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Owen K. Garriott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jack R. Lousma", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Oleg G. Makarov", 'country'] = "USSR"
astro_db.loc[astro_db['astronaut_name'] == "Gerald P. Carr", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Edward G. Gibson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William R. Pogue", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Vance D. Brand", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donald K. Slayton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Yury V. Malyshev", 'country'] = "USSR"

astro_db.loc[astro_db['astronaut_name'] == "C. Gordon Fullerton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas K. Mattingly II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Henry W. Hartsfield Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert F. Overmyer", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph P. Allen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William B. Lenoir", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Frederick H. Hauck", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John M. Fabian", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Norman E. Thagard", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard H. Truly", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Daniel C. Brandenstein", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Guion S. Bluford Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dale A. Gardner", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William E. Thornton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Francis R. Scobee", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Terry J. Hart", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James D. van Hoften", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "George D. Nelson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael L. Coats", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard M. Mullane", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Steven A. Hawley", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Judith A. Resnik", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "Charles D. Walker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David M. Walker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Anna L. Fisher", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Karol J. Bobko", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donald E. Williams", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Margaret R. Seddon", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "S. David Griggs", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jeffrey A. Hoffman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Frederick D. Gregory", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Don L. Lind", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Taylor G. Wang", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John O. Creighton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Steven R. Nagel", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Shannon W. Lucid", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sultan bin Salman Al Saud", 'country'] = "Saudi Arabia"
astro_db.loc[astro_db['astronaut_name'] == "Roy D. Bridges Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Karl G. Henize", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "F. Story Musgrave", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Anthony W. England", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Loren W. Acton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John-David F. Bartoe", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard O. Covey", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John M. Lounge", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William F. Fisher", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Aleksandr A. Volkov", 'country'] = "USSR"
astro_db.loc[astro_db['astronaut_name'] == "Bonnie J. Dunbar", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James F. Buchli", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Gibson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles F. Bolden Jr.", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "Franklin R. Chang Diaz", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Clarence W. Nelson II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert J. Cenker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael J. Smith", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ellison S. Onizuka", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ronald E. McNair", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Gregory B. Jarvis", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "S. Christa McAuliffe", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Alexander P. Aleksandrov", 'country'] = "USSR"
astro_db.loc[astro_db['astronaut_name'] == "Aleksandr P. Aleksandrov", 'country'] = "Bulgaria"
astro_db.loc[astro_db['astronaut_name'] == "Abdul Ahad Mohmand", 'country'] = "Afghanistan"
astro_db.loc[astro_db['astronaut_name'] == "John E. Blaha", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert C. Springer", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James P. Bagian", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Manley L. Carter Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kathryn C. Thornton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Aleksandr N. Balandin", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "John H. Casper", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Pierre J. Thuot", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David C. Hilmers", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard N. Richards", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert D. Cabana", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Bruce E. Melnick", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "William M. Shepherd", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas D. Akers", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Frank L. Culbertson Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Carl J. Meade", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles D. Gemar", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kenneth S. Reightler Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mark N. Brown", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Franz A. Viehböck", 'country'] = "Austria"
astro_db.loc[astro_db['astronaut_name'] == "Terence T. Henricks", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James S. Voss", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mario Runco Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas J. Hennen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kevin P. Chilton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard J. Hieb", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Curtis L. Brown Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mark C. Lee", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jerome Apt III", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "N. Jan Davis", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mae C. Jemison", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael R. Clifford", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jerry L. Ross", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles J. Precourt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Bernard A. Harris Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ronald J. Grabe", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "G. David Low", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Nancy J. Currie-Gregg", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Peter J. K. Wisoff", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Janice E. Voss", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard A. Searfoss", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William S. McArthur Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David A. Wolf", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Martin J. Fettman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kenneth D. Bowersox", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sidney M. Gutierrez", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Linda M. Godwin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas D. Jones", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James D. Halsell Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Carl E. Walz", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donald A. Thomas", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Yelena V. Kondakova", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "James D. Wetherbee", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Eileen M. Collins", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "C. Michael Foale", 'country'] = "UK"
astro_db.loc[astro_db['astronaut_name'] == "Kent V. Rominger", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Catherine G. Coleman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael E. López-Alegría", 'country'] = "Spain"
astro_db.loc[astro_db['astronaut_name'] == "Frederick W. Leslie", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Albert Sacco Jr.", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "Scott J. Horowitz", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph R. Tanner", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Gregory J. Harbaugh", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Steven L. Smith", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Susan L. Kilrain Still", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael L. Gernhardt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Roger K. Crouch", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Gregory T. Linteris", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Curbeam Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Stephen K. Robinson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael J. Bloomfield", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Scott E. Parazynski", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Wendy B. Lawrence", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Terrence W. Wilcutt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joe F. Edwards Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James F. Reilly II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael P. Anderson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Andrew S. W. Thomas", 'country'] = "Australia"
astro_db.loc[astro_db['astronaut_name'] == "Scott D. Altman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kathryn P. Hire", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard M. Linnehan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jay C. Buckey", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James A. Pawelczyk", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Frederick W. Sturckow", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James H. Newman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Rick D. Husband", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Daniel T. Barry", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ellen L. Ochoa", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Tamara E. Jernigan", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "Edward T. Lu", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard A. Mastracchio", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Daniel C. Burbank", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jeffrey S. Ashby", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John L. Phillips", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Yury V. Lonchakov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Dennis A. Tito", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Patrick G. Forrester", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Vladimir N. Dezhurov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Duane G. Carey", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John M. Grunsfeld", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael J. Massimino", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Pamela A. Melroy", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Piers J. Sellers", 'country'] = "UK"
astro_db.loc[astro_db['astronaut_name'] == "Sandra H. Magnus", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William B. Binnie", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Gregory H. Olsen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Lee J. Archambault", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Steven R. Swanson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John D. Olivas", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Clayton C. Anderson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "George D. Zamka", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Douglas H. Wheelock", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Stephanie D. Wilson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Daniel M. Tani", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dominic L. P. Gorie", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Gregory H. Johnson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Behnken", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael J. Foreman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Garrett E. Reisman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "E. Michael Fincke", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard A. Garriott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dominic A. Antonelli", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joseph M. Acaba", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Richard R. Arnold II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mark L. Polansky", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Douglas G. Hurley", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Christopher J. Cassidy", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Thomas H. Marshburn", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Timothy L. Kopra", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "Timothy J. Creamer", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sôichi Noguchi", 'country'] = "Japan"
astro_db.loc[astro_db['astronaut_name'] == "Alan G. Poindexter", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James P. Dutton Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dorothy M. Metcalf-Lindenburger", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Christopher J. Ferguson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Rex J. Walheim", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sunita L. Williams", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Karen L. Nyberg", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David W. D. Mackay", 'country'] = "UK"
astro_db.loc[astro_db['astronaut_name'] == "Sir Richard Branson", 'country'] = "UK"
astro_db.loc[astro_db['astronaut_name'] == "Robert M. White", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Anton N. Shkaplerov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "William H. Dana", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles M. Duke Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Arnaldo T. Méndez", 'country'] = "Cuba"
astro_db.loc[astro_db['astronaut_name'] == "Barry E. Wilmore", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Terry W. Virts Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mikhail B. Korniyenko", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Scott J. Kelly", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sergey A. Volkov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Andreas E. Mogensen", 'country'] = "Denmark"
astro_db.loc[astro_db['astronaut_name'] == "Aidyn A. Aimbetov", 'country'] = "Kazakhstan"
astro_db.loc[astro_db['astronaut_name'] == "Sergey N. Ryazansky", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Randolph J. Bresnik", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Nick Hague", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Christina H. Koch", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jessica U. Meir", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ivan V. Vagner", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Alan B. Shepard Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "M. Scott Carpenter", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donn F. Eisele", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Loren J. Shriver", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Bruce McCandless II", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ellen S. Baker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Lawrence J. Delucas", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Eugene H. Trinh", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael A. Baker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles L. Veach", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William F. Readdy", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Daniel W. Bursch", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Andrew M. Allen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Marsha S. Ivins", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "L. Blaine Hammond Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jerry M. Linenger", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Susan J. Helms", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donald R. McMonagle", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kevin R. Kregel", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles E. Brady Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Brent W. Jett", 'country'] = "United States of America"

astro_db.loc[astro_db['astronaut_name'] == "Carlos I. Noriega", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Steven W. Lindsey", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Winston E. Scott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Janet L. Kavandi", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John H. Glenn Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Viktor M. Afanasyev", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Mary E. Weber", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jeffrey N. Williams", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James M. Kelly", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Paul W. Richards", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Charles O. Hobaugh", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Stephen N. Frick", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Lee M. Morin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kenneth D. Cockrell", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Paul S. Lockhart", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Peggy A. Whitson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "John B. Herrington", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Donald R. Pettit", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William C. McCool", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "David M. Brown", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Laurel B. Clark", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael W. Melvill", 'country'] = "South Africa"
astro_db.loc[astro_db['astronaut_name'] == "Yuri Sharginy", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Charles J. Camarda", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Marcos C. Pontes", 'country'] = "Brazil"
astro_db.loc[astro_db['astronaut_name'] == "William A. Oefelein", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Nicholas J. M. Patrick", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Joan E. Higginbotham", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Tracy E. Caldwell Dyson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Barbara R. Morgan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Alvin Drew", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Leland D. Melvin", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Stanley G. Love", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William J. Knight", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sergey N. Ryzhikov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Michael S. Hopkins", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Victor J. Glover", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert A. Rushworth", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Dumitru D. Prunariu", 'country'] = "Romania"
astro_db.loc[astro_db['astronaut_name'] == "Donald H. Peterson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Stewart", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Gary E. Payton", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William A. Pailes", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Brewster H. Shaw Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Bryan D. O'Connor", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mary L. Cleave", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sherwood C. Spring", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Rodolfo Neri Vela", 'country'] = "Mexico"

astro_db.loc[astro_db['astronaut_name'] == "Guy S. Gardner", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "James C. Adamson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael J. McCulley", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Robert A. Parker", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Samuel T. Durrance", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ronald A. Parise", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kenneth D. Cameron", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "F. Andrew Gaffney", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Stephen S. Oswald", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Byron K. Lichtenberg", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "William G. Gregory", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ronald M. Sega", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mark E. Kelly", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael E. Fossum", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Lisa M. Nowak", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Heidemarie M. Stefanyshyn-Piper", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sheikh Muszaphar Shukor Al Masrie", 'country'] = "Malaysia"
astro_db.loc[astro_db['astronaut_name'] == "Eric A. Boe", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Stephen G. Bowen", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael R. Barratt", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Gregory C. Johnson", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Michael T. Good", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Andrew J. Feustel", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kevin A. Ford", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "José M. Hernández", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Nicole P. Stott", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Maksim V. Surayev", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Robert L. Satcher Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Aleksandr A. Skvortsov", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Kenneth T. Ham", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Ronald J. Garan Jr.", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Gregory E. Chamitoff", 'country'] = "Canada"
astro_db.loc[astro_db['astronaut_name'] == "Gregory R. Wiseman", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Kjell N. Lindgren", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Scott D. Tingle", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Mark P. Stucky", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Andrew R. Morgan", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Stuart A. Roosa", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Edgar D. Mitchell", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Jack D. Fischer", 'country'] = "United States of America"
astro_db.loc[astro_db['astronaut_name'] == "Sergey V. Prokopyev", 'country'] = "Russia"
astro_db.loc[astro_db['astronaut_name'] == "Serena M. Auñón-Chancellor", 'country'] = "United States of America"













